spring:
  application:
    name: widget
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://65.108.87.147:5432/ms-plugin}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:CPa6nMDiEN7Ee2hsWVMB}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 60000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    baseline-version: 1
logging:
  level:
    org:
      springframework:
        web: DEBUG
        orm: DEBUG
server:
  port: ${PORT:8080}
