-- Таблица конфигураций приложения
CREATE TABLE app_config
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    key        VARCHAR(255) UNIQUE                     NOT NULL, -- Уникальное ограничение для ключей
    value      VARCHAR(255),
    CONSTRAINT pk_app_config PRIMARY KEY (id)
);

-- Вставка значений по умолчанию для JWT
INSERT INTO app_config (id, created_at, updated_at, key, value)
VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'jwt.secret',
        'X36JfXAtiNJb2mDHkNwW9vQmRpLAhrXfJHQrXdPRUkzrrRJv1bEI5D5YshllvUPIo8XY4JR4d0DbXYABJRuyDdUG2lDZLFQcVf9qFwH4hbjvi3gl7eScSRgYeGJ79KeU');

INSERT INTO app_config (id, created_at, updated_at, key, value)
VALUES (2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'appUid', 'testvadim3.siriuslab');

-- Таблица активаций приложений
CREATE TABLE application_activation
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    app_uid        VARCHAR(255)                            NOT NULL,
    account_id     UUID                                    NOT NULL,
    account_name   VARCHAR(255),
    cause          VARCHAR(255),
    tariff_id      UUID,
    trial          BOOLEAN,
    tariff_name    VARCHAR(255),
    expiry_moment  TIMESTAMP WITH TIME ZONE,
    not_for_resale BOOLEAN,
    CONSTRAINT pk_application_activation PRIMARY KEY (id),
    CONSTRAINT uq_application_activation_account_id UNIQUE (account_id) -- Уникальное ограничение для account_id
);

-- Индекс для account_id
CREATE INDEX idx_account_id ON application_activation (account_id);

-- Таблица аккаунтов
CREATE TABLE account
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    account_id    UUID                                    NOT NULL,
    access_token  VARCHAR(255)                            NOT NULL,
    activated     BOOLEAN                                 NOT NULL,
    suspended     BOOLEAN                                 NOT NULL,
    activation_id BIGINT,
    CONSTRAINT pk_account PRIMARY KEY (id),
    CONSTRAINT uq_account_account_id UNIQUE (account_id) -- Уникальное ограничение для account_id
);

-- Внешний ключ для связи с application_activation
ALTER TABLE account
    ADD CONSTRAINT FK_ACCOUNT_ON_ACTIVATION FOREIGN KEY (activation_id) REFERENCES application_activation (id);

-- Таблица настроек аккаунта
CREATE TABLE account_settings
(
    account_id        BIGINT  NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    customer_order    BOOLEAN NOT NULL,
    customer_order_in BOOLEAN NOT NULL,
    demand            BOOLEAN NOT NULL,
    demand_in         BOOLEAN NOT NULL,
    sales_return      BOOLEAN NOT NULL,
    sales_return_in   BOOLEAN NOT NULL,
    supply            BOOLEAN NOT NULL,
    supply_in         BOOLEAN NOT NULL,
    purchase_return   BOOLEAN NOT NULL,
    enter             BOOLEAN NOT NULL,
    payment_in        BOOLEAN NOT NULL,
    payment_in_in     BOOLEAN NOT NULL,
    payment_out       BOOLEAN NOT NULL,
    payment_out_in    BOOLEAN NOT NULL,
    cash_in           BOOLEAN NOT NULL,
    cash_in_in        BOOLEAN NOT NULL,
    cash_out          BOOLEAN NOT NULL,
    cash_out_in       BOOLEAN NOT NULL,
    purchase_order    BOOLEAN NOT NULL,
    loss              BOOLEAN NOT NULL,
    move              BOOLEAN NOT NULL,
    processing        BOOLEAN NOT NULL,
    good              BOOLEAN NOT NULL,
    good_in           BOOLEAN NOT NULL,
    company           BOOLEAN NOT NULL,
    company_in        BOOLEAN NOT NULL,
    contract          BOOLEAN NOT NULL,
    contract_in       BOOLEAN NOT NULL,
    processing_plan   BOOLEAN NOT NULL,
    bundle            BOOLEAN NOT NULL,
    CONSTRAINT pk_account_settings PRIMARY KEY (account_id)
);

-- Внешний ключ для связи с account
ALTER TABLE account_settings
    ADD CONSTRAINT FK_ACCOUNT_SETTINGS_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (id);

-- Таблица истории деактиваций
CREATE TABLE deactivation_history
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    account_id    UUID                                    NOT NULL,
    account_name  VARCHAR(255)                            NOT NULL,
    cause         VARCHAR(255)                            NOT NULL,
    activation_id BIGINT,
    CONSTRAINT pk_deactivation_history PRIMARY KEY (id)
);

-- Внешний ключ для связи с application_activation
ALTER TABLE deactivation_history
    ADD CONSTRAINT FK_DEACTIVATION_HISTORY_ON_ACTIVATION FOREIGN KEY (activation_id) REFERENCES application_activation (id);