ALTER TABLE account_settings
    ADD COLUMN IF NOT EXISTS production_task BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE account_settings
    ADD COLUMN IF NOT EXISTS move BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE account_settings
    ADD COLUMN IF NOT EXISTS retail_demand BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE account_settings
    ADD COLUMN IF NOT EXISTS retail_sales_return BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE account_settings
    ADD COLUMN IF NOT EXISTS facture_out BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE account_settings
    ADD COLUMN IF NOT EXISTS abstract_inventory BOOLEAN DEFAULT FALSE NOT NULL;